version: '3.7'

services:

  ## Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "7300:9411"
    volumes:
      - ./var/config/zipkin:/var/lib/zipkin  
    network_mode: localhost  

  ## Prometheus
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: always
    ports:
      - "7400:9090"
    volumes:
      - ./var/config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - config-cloud
      - gateway-cloud
      - order-service
      - eureka-cloud
    network_mode: localhost  

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: always
    ports:
      - "7500:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./var/config/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    network_mode: localhost  
